"<?php include "../inc/dbinfo.inc"; ?>\n",
"<html>\n",
"<body>\n",
"<h1>Sample page</h1>\n",
"<?php\n",
"\n",
"  /* Connect to MySQL and select the database. */\n",
"  $connection = mysqli_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD);\n",
"\n",
"  if (mysqli_connect_errno()) echo "Failed to connect to MySQL: " . mysqli_connect_error();\n",
"\n",
"  $database = mysqli_select_db($connection, DB_DATABASE);\n",
"\n",
"  /* Ensure that the Employees table exists. */\n",
"  VerifyEmployeesTable($connection, DB_DATABASE);\n",
"\n",
"  /* If input fields are populated, add a row to the Employees table. */\n",
"  $employee_name = htmlentities($_POST['Name']);\n",
"  $employee_address = htmlentities($_POST['Address']);\n",
"\n",
"  if (strlen($employee_name) || strlen($employee_address)) {\n",
"    AddEmployee($connection, $employee_name, $employee_address);\n",
"  }\n",
"?>\n",
"\n",
"<!-- Input form -->\n",
"<form action="<?PHP echo $_SERVER['SCRIPT_NAME'] ?>" method="POST">\n",
"  <table border="0">\n",
"    <tr>\n",
"      <td>Name</td>\n",
"      <td>Address</td>\n",
"    </tr>\n",
"    <tr>\n",
"      <td>\n",
"        <input type="text" name="Name" maxlength="45" size="30" />\n",
"      </td>\n",
"      <td>\n",
"        <input type="text" name="Address" maxlength="90" size="60" />\n",
"      </td>\n",
"      <td>\n",
"        <input type="submit" value="Add Data" />\n",
"      </td>\n",
"    </tr>\n",
"  </table>\n",
"</form>\n",
"\n",
"<!-- Display table data. -->\n",
"<table border="1" cellpadding="2" cellspacing="2">\n",
"  <tr>\n",
"    <td>ID</td>\n",
"    <td>Name</td>\n",
"    <td>Address</td>\n",
"  </tr>\n",
"\n",
"<?php\n",
"\n",
"$result = mysqli_query($connection, "SELECT * FROM Employees");\n",
"\n",
"while($query_data = mysqli_fetch_row($result)) {\n",
"  echo "<tr>";\n",
"  echo "<td>",$query_data[0], "</td>",\n",
"       "<td>",$query_data[1], "</td>",\n",
"       "<td>",$query_data[2], "</td>";\n",
"  echo "</tr>";\n",
"}\n",
"?>\n",
"\n",
"</table>\n",
"\n",
"<!-- Clean up. -->\n",
"<?php\n",
"\n",
"  mysqli_free_result($result);\n",
"  mysqli_close($connection);\n",
"\n",
"?>\n",
"\n",
"</body>\n",
"</html>\n",
"\n",
"\n",
"<?php\n",
"\n",
"/* Add an employee to the table. */\n",
"function AddEmployee($connection, $name, $address) {\n",
"   $n = mysqli_real_escape_string($connection, $name);\n",
"   $a = mysqli_real_escape_string($connection, $address);\n",
"\n",
"   $query = "INSERT INTO `Employees` (`Name`, `Address`) VALUES ('$n', '$a');";\n",
"\n",
"   if(!mysqli_query($connection, $query)) echo("<p>Error adding employee data.</p>");\n",
"}\n",
"\n",
"/* Check whether the table exists and, if not, create it. */\n",
"function VerifyEmployeesTable($connection, $dbName) {\n",
"  if(!TableExists("Employees", $connection, $dbName))\n",
"  {\n",
"     $query = "CREATE TABLE `Employees` (\n",
"         `ID` int(11) NOT NULL AUTO_INCREMENT,\n",
"         `Name` varchar(45) DEFAULT NULL,\n",
"         `Address` varchar(90) DEFAULT NULL,\n",
"         PRIMARY KEY (`ID`),\n",
"         UNIQUE KEY `ID_UNIQUE` (`ID`)\n",
"       ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1";\n",
"\n",
"     if(!mysqli_query($connection, $query)) echo("<p>Error creating table.</p>");\n",
"  }\n",
"}\n",
"\n",
"/* Check for the existence of a table. */\n",
"function TableExists($tableName, $connection, $dbName) {\n",
"  $t = mysqli_real_escape_string($connection, $tableName);\n",
"  $d = mysqli_real_escape_string($connection, $dbName);\n",
"\n",
"  $checktable = mysqli_query($connection,\n",
"      "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME = '$t' AND TABLE_SCHEMA = '$d'");\n",
"\n",
"  if(mysqli_num_rows($checktable) > 0) return true;\n",
"\n",
"  return false;\n",
"}\n",
"?>\n"